title: "Gayani Rathnasekara"
author: "Gayani Rathnasekara"
email: grath003@fiu.edu
markdown: kramdown
kramdown:
  parse_block_html: true


description: >
  Welcome to Gayani's Website!!! Website for sharing my personal, professional, and academic journey.  

theme: minima
google_fonts:
  - Inter:400,500,600


header_pages:
  - about.md
  - education.md
  - experience.md
  - skills.md
  - projects_research.md
  - publications.md
  - conferences_seminars.md
  - awards.md
  - hobbies.md
  - volunteering.md

github_username: Gayani-Rathnasekara
linkedin_username: gayani-rathnasekara
